[build]
  functions = "netlify/functions"

[[functions]]
  included_files = ["netlify/functions/**"]
  node_bundler = "esbuild"

[functions]
  external_node_modules = ["axios"]

[functions.chat]
  timeout = 1200